### ISSUE TITLE
Add footprint for microSD socket

### ISSUE THREAD

**Issue by matthiasbock** [matthiasbock/Altium-Libraries#7]
![microsd footprint](https://cloud.githubusercontent.com/assets/1587578/14060764/84ffa546-f36e-11e5-8c22-514889b69767.jpg)
![microsd measurements](https://cloud.githubusercontent.com/assets/1587578/14060765/88a01384-f36e-11e5-9313-f958b2b9f8be.jpg)

**Comment by matthiasbock** [comment]
Possible 3D models:
- https://grabcad.com/library/micro-sd-card-slot-1
- https://grabcad.com/library/micro-sd-slot-with-sd-card

**Comment by DRSDavidSoft** [comment]
<table>
<tr>
<td>
<img width="306" height="400" alt="Micro SD Card, TF Card, Memory Card Connector, 9-Leads, Body 16.44x15.6 mm, 1.4mm Profile SMT, Push-Push (MEM2055/MEM2075)" src="https://github.com/matthiasbock/Altium-Libraries/assets/4673812/4a38c0b9-1a4e-41ea-87d3-6bb4a9d48a85">
</td>
<td>
<img width="509" height="288" alt="image" src="https://github.com/matthiasbock/Altium-Libraries/assets/4673812/9510f7da-4a0e-4276-a641-75d6881a2d22">
</td>
</tr>
<tr>
<td colspan="2">
<strong>Library:</strong> <a href="https://github.com/matthiasbock/Altium-Libraries/files/13064402/MicroSD_Connector.zip"><kbd><strong>📦 MicroSD_Connector.zip</strong> – Download 1.90MB</kbd></a> (Contains PcbLib + SchLib)
</td>
</tr>
</table>

This is the best I was able to do with the dimensions that you provided. At first the footprint would match [MEM2075](https://gct.co/connector/mem2075), but it appears the mounting holes differ between these parts.

Here's the results, below. It looks to nicely fit the footprint, however the `SH` pads (identified as `G` in the drawing above) might need to be expanded if the socket is soldered by hand. In my case I was a bit space restraint so I only added a margin of `.2mm` for the solder.

<table>
<tr>
<td>
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/4673812/277238827-4fe5c9fb-b341-4cb4-8cc9-524fdd20922e.png" />
<h3>Left-side and Right-side</h3>
</td>
<td>
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/4673812/277238875-99ef9ae3-7cae-4c59-b381-b7e6ad3d8bd4.png" />
<h3>Top and Bottom</h3>
</td>
</tr>
</table>


I didn't make a PR because I wasn't sure if this repo was maintained. If so, please feel free to include this footprint in your library. I release it under the same GPL-3 that it used by you. Similarly, the included steps might be copyrighted, I'm not sure.

<img width="540" alt="image" src="https://github.com/matthiasbock/Altium-Libraries/assets/4673812/a6538e25-0f4c-4ac2-a807-8619bd4bfc5f">

**Comment by matthiasbock** [comment]
This is awesome!
Thank you for your contribution!
